seed: 7
num_workers: -1
log_offline: false
joern_path: ~/joern/joern-parse
split_token: false
cleaning_method: raw
temp_root: temp/data
pert_CPG_root: pert_CPG
repo_root: SySeVRCopy
data_folder: data
model_save_dir: saved_models
diff_folder: diff
source_root_folder: source-code
csv_folder: csv
slice_folder: slice
deepwukong_slice_folder: XFG
VF_perts_root: VF_perts
SF_perts_root: SF_perts
nodes_filename: nodes.csv
edges_filename: edges.csv
cpp_paths_filename: cpp_paths.json
xml_filename: SARD_testcaseinfo.xml
file_slices_filename: file_slices.json
all_slices_filename: all_slices.json
train_slices_filename: train_slices.json
val_slices_filename: val_slices.json
test_slices_filename: test_slices.json
ground_truth_filename: ground_truth.json
function_metadata_filename: function_metadata.json
dataset_filename: function.json
bigvul_dataset_filename: processed_data.csv
unperturbed_files_filename: unperturbed_file_list.json
sensi_api_filename: sensi_api.json
sensi_api_map_filename: sensi_api_map.json
instance_perturbation_map_filename: instance_perturbation_map.json
swav_batches_filename: swav_multicrop_batches.json
pairs_filename: vv_vn_pairs.json
ignore_list_filename: ignore_list.json
ignore_list_detection_result_filename: ignore_list_detection_result.json
detection_result_filename: detection_result.json
perturbation_result_filename: perturbation_result.json
save_every_epoch: 1
val_every_epoch: 1
log_every_epoch: 10
progress_bar_refresh_rate: 1
exclude_NNs: false
dataset:
  name: BigVul
  token:
    max_parts: 16
    is_wrapped: false
    is_splitted: false
    vocabulary_size: 190000
min_vul_per_batch: 3
min_nonvul_per_batch: 1
swav:
  batch_size: 256
  learning_rate: 0.001
  warmup_epochs: 0
  start_warmup: 0
  base_lr: 0.6
  final_lr: 0.0006
  wd: 1e-6
  freeze_prototypes_niters: 5005
  num_prototypes: 128
  hidden_mlp: 2048
  projection_dim: 128
  nmb_prototypes: 3000
  l2norm: true
  temperature: 0.1
  weight_factor: 0.7
  sinkhorn:
    n_iters: 10
    epsilon: 0.03
    temperature: 10.0
  contrastive:
    temperature: 0.1
    lambda_h: 1.0
    alpha: 0.25
    omega: 0.25
    criterion: info_nce
  margin: 0.5
  alpha: 0.25
  omega: 0.25
  vul_beta: 0.007
  nonvul_beta: 0.005
  vul_gamma: 0.015
  nonvul_gamma: 0.01
  n_epochs: 10
  use_prototype_loss: true
  model_save_path: GraphSwAV.ckpt
  prototypes_save_path: GraphSwAV_prototypes.ckpt
  assignment_protocol: sinkhorn
  nmb_views:
  - 2
  - 2
  views_for_assign:
  - 0
  - 1
gnn:
  name: gine
  edge_dim: 2
  w2v_path: ${data_folder}/${dataset.name}/w2v.wv
  embed_size: 256
  hidden_size: 256
  pooling_ratio: 0.8
  attention_only: true
  use_edge_attr: true
  train_eps: true
  drop_out: 0.5
  n_hidden_layers: 3
  n_head: 3
  n_gru: 3
  edge_sample_ratio: 0.8
  rnn:
    hidden_size: 256
    num_layers: 1
    drop_out: 0.5
    use_bi: true
    activation: relu
classifier:
  hidden_size: 512
  n_hidden_layers: 2
  n_classes: 2
  drop_out: 0.5
hyper_parameters:
  use_imbalanced_sampler: false
  lambdas:
    classification: 1.0
    projection: 1.0
    regularization: 0.01
    swav: 0.7
    contrastive: 0.7
  temperature: 0.2
  vector_length: 128
  n_epochs: 100
  patience: 10
  batch_sizes:
    - 128
    - 128
    - 128
    - 128
    - 128
    - 128
    - 128
    - 128
    - 128
    - 128
  test_batch_size: 128
  reload_dataloader: true
  clip_norm: 5
  val_every_step: 1.0
  log_every_n_steps: 50
  progress_bar_refresh_rate: 1
  resume_from_checkpoint: CLVulDet
  shuffle_data: true
  optimizer: Adam
  nesterov: true
  use_warmup_lr: false
  contrastive_warmup_epochs: 0
  projection_weight_factor: 1.0
  regularization_weight_factor: 0.01
  learning_rate: 0.002
  weight_decay: 0
  decay_gamma: 0.95
vul_feats:
  - incorr_calc_buff_size
  - buff_access_src_size
  - off_by_one
  - buff_overread
  - double_free
  - use_after_free
  - buff_underwrite
  - buff_underread
  - sensi_read
  - sensi_write
train_sampler_options:
  - instance
  - vf
  - swav
use_custom_tokenizer: true
tokenizer_name: microsoft/codebert-base
implemented_preprocessing:
  - remove_dependency_free_nodes
  - remove_unsatisfieable_conditions
  - refine_slicing
implemented_vectorizers:
  - word2vec
  - code2vec
  - bpe
  - codebert
  - pdbert
  - graphcodebert
implemented_models:
  - gcn
  - ggnn
implemented_distance_metrics:
  - cosine
  - euclidean
  - kullback
preprocessing:
  - remove_dependency_free_nodes
  - remove_unsatisfieable_conditions
  - refine_slicing
vectorizer: word2vec
distance_metric: cosine